name: Linting and other checks

on: push

jobs:
  build:
    name: Linting and other checks
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup bun environment
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint eslint
        run: bun run lint:eslint

      - name: Lint formatting
        run: bun run lint:formatting

      - name: Type check
        run: bun run check
